define(["../logic/addque","../components/commonCtl"],function(pluginClass,c){
    return {
        pluginClass:pluginClass,
        style:{
            backgroundColor:"#f0f4f6"
        },
        root:["page_content"],
        components:{
          test:{
            type:"text",
            "text":"条"
          },
            page_content:{
              type:"view",
              style:{
                flex:1,
                overflowY:"auto",
                paddingBottom:40,
              },
              root:["queName","splitLine","queDesc","splitLine2","addlabel_wrapper","splitLine1","imagesRepeat"]
            },
            imagesRepeat:{
              type:"repeat",
              ref:true,
              subComponentAlwaysShow:true,
              items:[],
              root:["image","imageDelIcon"],
              style:{
                flexDirection:"row",
                flexWrap:"wrap",
                marginTop:5,
                paddingLeft:5
              },
              itemStyle:{
                w:90,
                justifyContent:"center",
                alignItems:"center",
              },
              subComponent:"addImageIcon"
            },
            addImageIcon:{
              type:"icon",
              text:"＋",
              style:{
                w:80,
                backgroundColor:"#fff",
                marginTop:5,
                marginLeft:5,
                border:"1px dashed rgb(207,207,207)",
              },
              textStyle:{
                color:"rgb(207,207,207)",
                fontSize:49
              },
            },
            imageDelIcon:{
              type:"icon",
              font:"icomoon_e909",
              style:{
                position:"absolute",
                right:8,
                border:"2px solid #fff",
                borderRadius:"100%",
                backgroundColor:"#fff",
                top:8
              },
              iconStyle:{
                color:"#FC505F",
                fontSize:17
              }
            },
            image:{
              type:"image",
              src_bind:"src",
              src:"",
              style:{
                w:80,
                backgroundColor:"rgba(0,0,0,.1)"
              }
            },
            splitLine:{
              type:"view",
              className:"qaa_splitline",
            },
            splitLine2:{
              type:"view",
              className:"qaa_splitline",
            },
            splitLine1:{
              type:"view",
              className:"qaa_splitline",
            },
            queName:{
              type:"textarea",
              ref:true,
              max:50,
              limitStyle:{
                right:10,
                color:"#aaa"
              },
              numStyle:{

              },
              maxStyle:{

              },
              placeholder:"您的问题 ( 50个字以内 )",
              style:{
                height:100,
                paddingLeft:15,
                paddingRight:10,
                fontSize:15,
                paddingTop:15,
              },
            },
            imagewrapper:{
              type:"view",
              style:{
                height:50,
                flexDirection:"row",
                justifyContent:"flex-start",
                paddingLeft:15,
                backgroundColor:"#fff"
              },
              root:["photoIcon","CameraIcon"]
            },
            photoIcon:{
              type:"icon",
              font:"icomoon_e907",
              activeClassName:"qaa_picicon_active",
              style:{
                width:35,
              },
              iconStyle:{
                fontSize:30,
                w:35,
                justifyContent:"center",
                color:"#ccc"
              }
            },
            CameraIcon:{
              type:"icon",
              font:"icomoon_e905",
              activeClassName:"qaa_picicon_active",
              style:{
                marginLeft:12,
                width:35,
              },
              iconStyle:{
                fontSize:30,
                w:35,
                justifyContent:"center",
                color:"#ccc",
              }
            },
            addlabel_wrapper:{
              type:"view",
              style:{
                flexDirection:"row",
                paddingLeft:15,
                paddingRight:10,
                minHeight:51,
                backgroundColor:"#fff",
              },
              root:["addlabel_text","label_repeat","right_icon"]
            },
            right_icon:{
              type:"icon",
              style:{
                width:20
              },
              font:"icomoon_e913",
            },
            label_repeat:{
              type:"repeat",
              ref:true,
              items:[],
              style:{flex:1,flexWrap:"wrap",alignContent:"center",alignItems:"center"},
              itemStyle:{
                marginBottom:5,
                marginTop:5
              },
              root:["label"]
            },
            label:{
              type:"text",
              text_bind:"title",
              text:"标签",
              style:c.historyLableStyle,
            },
            addlabel_text:{
              type:"text",
              text:"添加标签",
              style:{
                color:c.titleColor,
                fontSize:15,width:85
              }
            },
            queDesc:{
              type:"textarea",
              ref:true,
              placeholder:"补充描述 ( 选填 )",
              style:{
                height:160,
                paddingRight:10,
                paddingLeft:15,
                fontSize:15,
                paddingTop:15,
              },
            },
        }
    };
});
