define(["../logic/search","../components/commonCtl",'utils','../parts/listview'],function(pluginClass,c,utils,listview){
    var config = {
        pluginClass:pluginClass,
        style:{
            backgroundColor:"#f2f3f4"
        },
        root:["page_content"],
        components:{
            page_content:{
              type:"view",
              style:{
                flex:1,
              },
              root:["searchview"]
            },
            searchview:{
              type:"searchview",
              time:700,
              style:{
                flex:1,
                backgroundColor:"#fff"
              },
              searchBarStyle:{
                height:50
              },
              bodyStyle:{
                backgroundColor:"#f2f3f4"
              },
              resultComponent:"body",
              defaultComponent:"hostsearch",
            },
            hostsearch:{
              type:"view",
              style:{
                flex:1
              },
              root:["hotsearch_title","historySearch_repeat_wrapper"]
            },
            historySearch_repeat_wrapper:{
              type:"view",
              style:{
                flex:1,
                overflowY:"auto"
              },
              root:["historySearch_repeat"]
            },
            hotsearch_title:{
              type:"text",
              text:"搜索历史记录",
              style:{
                height:30,
                paddingLeft:12,
                fontSize:13,
                color:c.descColor
              },
            },
            historySearch_repeat:{
              type:"repeat",
              style:{
                backgroundColor:"#fff",
                flexDirection:"column",

              },
              root:["historyItem"],
              nodata:"historyNoData",
              subComponent:"clearHistoryBtn",
              itemStyle:{
                height:50,
                justifyContent:"center",
                paddingLeft:12
              },
              splitStyle:{
                marginLeft:10,
                borderTop:"1px solid #F2F3F4",
              },
            },
            clearHistoryBtn:{
              type:"icon",
              text:"清除历史记录",
              style:{
                height:50,
                borderTop:"1px solid #F2F3F4"
              },
              textStyle:{
                fontSize:15,
                color:c.mainColor,
              }
            },
            historyItem:{
              type:"text",
              text_bind:"title",
              numberofline:1,
              style:{
                width:"100%",
                fontSize:15,
                color:c.titleColor
              }
            },
            historyNoData:{
              type:"text",
              text:"暂无历史搜索记录",
              style:{
                marginTop:"20",
                marginBottom:"20",
                fontSize:14,
                width:"100%",
                justifyContent:"center",
                color:c.labelColor
              },
            },
            body:{
              type:"view",
              style:{
                flex:1,
                overflowY:"auto"
              },
              root:["search_listview"]
            },
            list_nodata:{
              type:"text",
              style:{
                margin:"10% auto",
                textAlign:"center",
                width:"210",
                fontSize:15,
                justifyContent:"center",
                color:c.seTitleColor
              },
              text:"没有相关回答"
            },

        }
    };
    var ajaxConfig = {
      url:"/question/search",
      pageSize:20,
      type:"POST",
      pageNumKey:"pageNo",
      data:{
        title:'',
        pageNo:1,
        pageSize:20
      }
    };
    return utils.concat(config,listview.getList(false,ajaxConfig,"list_nodata"),"search_");
});
